version: "3"

networks:
  backend:
    driver: overlay

services:
   db:
    image: mysql:8.0
    hostname: mysqlserver
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myconnectpoc1
      MYSQL_DATABASE: EventLoggerDB
      MYSQL_USER: eventLogger
      MYSQL_PASSWORD: eventloggerpoc1
    volumes:
      - /home/pg_admin/db-vol/mysql/8.0/data:/var/lib/mysql
      - /home/pg_admin/db-vol/mysql/8.0/logs:/var/log/mysql:rw
      - /home/pg_admin/db-vol/mysql/8.0/conf.d:/etc/mysql/conf.d:ro
      - /home/pg_admin/db-vol/mysql/8.0/initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - backend
    
